//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int ID_Utilisateur { get; set; }
        public string Nom_Utilisateur { get; set; }
        public string Prenom_Utilisateur { get; set; }
        public string Mot_De_Passe { get; set; }
        public int ID_Profil { get; set; }
    
        public virtual Profil Profil { get; set; }
    }
}
